### ISSUE TITLE
Incremental compilation + multiple codegen units

### ISSUE THREAD

**Issue by theduke** [antoyo/tql#16]
I asked this on reddit, but since I'm not sure that you'll read it:

I've scanned the code and noticed that to make the `sql!` macro work, you are storing table and column information in global statics inside the `tql_macros` crate.

Wouldn't this break with conditional compilation, and also potentially with multiple codegen units?
Or does custom derive / proc macro expansion happen each time and so the state is always there?

Also I guess this means that tql can only be used within one crate, namely the one that defines the tables?

**Comment by antoyo** [comment]
Thanks for pointing out this issue.
I tested with incremental compilation and it seemed to work.
However, it does not work with multiple crates.

So, I will remove the internal state of the proc-macro to solve this issue.

**Comment by theduke** [comment]
Isn't the globabl state required though? Where else are you going to get the type information from?

**Comment by antoyo** [comment]
We can do without. I'll use the same trick I used to type-check the arguments (variables).

**Comment by antoyo** [comment]
It should be fixed by PR #23.

**Comment by theduke** [comment]
Just out of curiosity, how did you implement it now?
