### ISSUE TITLE
Chat space

### ISSUE THREAD

**Issue by Ygg01** [antoyo/tql#22]
Well, I have a need to ask stuff about TQL, so we might need a place to chat, with history that isn't the Github Repository. 

One way to do it, is Slack, but I'm unsure if all are comfortable using it, etc. I've setup an [tql-rs.slack.com (invite link)](https://join.slack.com/t/tql-rs/shared_invite/enQtMjkyMTUwODc0MDUzLTkzMGM5MWQ2Zjk3YmJmZDhhNTY1YjQ1YWZjMDY5ZTA4NTAzYzg4ZTgwYjU5OTFmN2JhMDU0OTQ4YjNiMWY2MzY)

**Comment by antoyo** [comment]
Oops, I've just noticed I forgot to add the link to [the gitter](https://gitter.im/tql-rs/Lobby) in the readme.
I'll add it soon.
